Todoproject/TodoApp/urls.py
from django.urls import path
from . import views
app_name='shop'
urlpatterns = [
    path('',views.Home,name='home'),
    path('<slug:c_slug>/',views.Home,name='product_by_category'),
    path('details/<int:id>',views.Details,name='details'),

]

Todoproject/Todoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('TodoApp.urls')), 
    path('auth/',include('userarauth.urls')), 
    path('searchapp/',include('searchapp.urls')), 
    path('cartapp/',include('cartapp.urls')), 
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Todoproject/cartapp/urls.py
from .import views
from django.urls import path
app_name='cartapp'
urlpatterns = [
    path('addcart/<int:id>',views.addcart,name='addcart'),
    path('removecart/<int:id>',views.removecart,name='removecart'),
    path('fullremove/<int:id>',views.fullremove,name='fullremove'),
    path('displaycart/',views.displaycart,name='displaycart'),
    path('placeorder/',views.placeorder,name='placeorder'),
]

Todoproject/searchapp/urls.py
from django.urls import path
from . import views
app_name='searchapp'
urlpatterns = [
    path('searchproduct/',views.SearchResult,name='searchproduct'),
]

Todoproject/userarauth/urls.py
from django.urls import path
from.import views

app_name='auth'
urlpatterns = [
    path('register/',views.registerUser,name='register'),
    path('login/',views.loginUser,name='login'),
    path('logout/',views.logoutUser,name='logout'),

    
    
]

Todoproject/TodoApp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)
    class Meta:
        ordering=('name',)
        
        
    def __str__(self):
        return self.name
    def get_url(self):
        return reverse('shop:product_by_category',args=[self.slug])


class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='product',blank=True)
    price=models.DecimalField(max_digits=8,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    class Meta:
        ordering=('name',)
        
        
    def __str__(self):
        return self.name

Todoproject/cartapp/models.py
from django.db import models

from TodoApp.models import Product
# Create your models here.
class Cart(models.Model):
    user=models.CharField(max_length=200)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    class Meta:
        db_table='cart'


# def __str__(self):
#     return self.product

Todoproject/searchapp/models.py
from django.db import models

# Create your models here.

Todoproject/userarauth/models.py
from django.db import models

# Create your models here.

Todoproject/TodoApp/views.py
from django.shortcuts import render,get_object_or_404
from .models import Product,Category
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.
def Home(request,c_slug=None):
    c_page=None
    product_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        print(c_page)
        product_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        product_list=Product.objects.all().filter(available=True) 
          #paginator
    paginator=Paginator(product_list,6)

    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    #for invalid page and empty page
        
    try:
        products=paginator.page(page)
    except:
        page=1
    #for invalid page and empty page
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)     
    return render(request,'index.html',{'data':product_list,'category':c_page,'products':products})



def Details(req,id):
    data=Product.objects.get(id=id)
    return render(req,'details.html',{'data':data})

Todoproject/cartapp/views.py
from django.shortcuts import render,redirect
from TodoApp.models import Product
from .models import Cart
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def addcart(req,id):
    user=req.session['user']
    product=Product.objects.get(id=id)
    print(product)
    try:
        cart=Cart.objects.get(product=product)
        if cart.quantity<cart.product.stock:
            cart.quantity+=1
            cart.save()
    except Cart.DoesNotExist:
        cart=Cart.objects.create(user=user,product=product,quantity=1)
    return redirect('cartapp:displaycart')
    
def displaycart(req):
    user=req.session['user']
    cart=Cart.objects.all().filter(user=user)
    return render(req,'cart.html',{'cart':cart})
def removecart(req,id):
    user=req.session['user']
    product=Product.objects.get(id=id)
    cart=Cart.objects.get(product=product,user=user)
    if cart.quantity>1:
        cart.quantity-=1
        cart.save()
    return redirect('cartapp:displaycart')

def fullremove(req,id):
    user=req.session['user']
    product=Product.objects.get(id=id)
    cart=Cart.objects.get(product=product,user=user)
    cart.delete()
    return redirect('cartapp:displaycart')     

def placeorder(req):
    user=req.session['user']
    cart=Cart.objects.filter(user=user)
    for carts in cart:
        carts.delete()
    return redirect('cartapp:displaycart')

Todoproject/searchapp/views.py
from django.shortcuts import render
from TodoApp.models import Product
from django.db.models import Q

# Create your views here.
def SearchResult(req):
    products=None
    query=None
    if 'q' in req.GET:
        query=req.GET.get('q')
        print(query)
        products=Product.objects.all().filter(Q(name__contains=query)|Q(desc__contains=query))


        return render(req,'search.html',{'query':query,'products':products})

Todoproject/userarauth/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.

def registerUser(req):
    if req.method=='POST':
        fname=req.POST.get("fname","")
        lname=req.POST.get("lname","")
        email=req.POST.get("email","")
        username=req.POST.get("username","")
        password=req.POST.get("password","")
        cpassword=req.POST.get("cpassword","")
        print(fname,lname,email,username,password,cpassword)
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(req,"username already exist")
                return redirect('auth:register')
            elif User.objects.filter(email=email).exists():
                messages.info(req,"email already exist")
                return redirect('auth:register')
            else:
                user=User.objects.create_user(first_name=fname,last_name=lname,email=email,username=username,password=password)
                user.save()
                return redirect('auth:login')
        else:
            messages.info(req,"password not matched")
            return redirect('auth:register')
    return render(req, 'registeruser.html')
def loginUser(req):
    if req.method=='POST':
        username=req.POST.get("username","")
        password=req.POST.get("password","")
        user=auth.authenticate(username=username,password=password)
        print(user)
        if user is not None:
          auth.login(req,user)
          print(user)
          req.session['user']=str(user)
          return redirect("shop:home")
        else:
            messages.info(req, "invalidcredentials")
            return redirect('auth:login')
    return render(req, 'loginuser.html')
def logoutUser(req):
    auth.logout(req)
    req.session.pop('user',None)
    return redirect("shop:home")

Todoproject/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css\style.css' %}">
  </head>
  <body>
    {% include 'nav.html' %}
    {% block content %}

    {% endblock %}
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

Todoproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<div class="row">
    <div class="col-lg-11">
        <h1 class="yr mt-3 mb-5">YOUR  PURCHASE  CART</h1>
        <table class="tbl table w-75">
            <thead class="thead-light">
                <tr class="trr bg-secxondary">
                    <th scope="col" style="width: 350px;">
                        <h3>Product</h3>
                    </th>
                    <th scope="col">
                        <h3>Quantity</h3>
                    </th>
                    <th scope="col">
                        <h3>Price</h3>
                    </th>
                    <th scope="col">
                        <h3>Cancel</h3>
                    </th>
                    <th scope="col">
                        <h3>Buy now</h3>
                    </th>
                </tr>
            </thead>


            <tbody>
                <tr>
                    {% for cartitem in cart %}
                    <th scope="row">
                        <img class="crtimg me-3 shadow" style="width: 85px;" src="{{cartitem.product.image.url}}"alt="">{{cartitem.product}}
                    </th>
                    <td>{{cartitem.product}}</td>
                    <td>${{cartitem.product.price}}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'cartapp:removecart' cartitem.product.id %}">-</a>
                        <span>{{cartitem.quantity}}</span>
                        <a class="btn btn-primary" href="{% url 'cartapp:addcart' cartitem.product.id %}">+</a>
                    </td>
                    <td>${{cartitem.product.price}}</td>
                    <td>
                        <a class="btn btn-danger" href="{% url 'cartapp:fullremove' cartitem.product.id %}">Remove</a>
                    </td>

                        
                        

<!-- 

                    <td>
                        <h4 class="mt-4 ms-4">{{cartitem.quantity}}</h4>
                    </td>
                    <td>
                        <h4 class="mt-4">{{cartitem.product.price}}</h4>
                    </td>
                    <td><a href="" class="btn btn-danger">Cancel</a></td>
                    <td><button class="btn btn-success">Buy Now</button></td> -->

                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>





    <a href="{% url 'shop:home' %}" class="purch btn btn-primary pt-2 pb-2 ps-2 pe-2 ">
        <h4>continue purchase</h4>
    </a>
    <a href="{% url 'cartapp:placeorder' %}" class="plac btn btn-warning pt-2"><h4>place order</h4></a>

</div>


    {% endblock %}

Todoproject/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="conta container-fluid mb-3 justify-content-center bg-light d-flex ">
    <div class="card crd rounded-2 bg-light ms-4 w-50 me-4 mb-5 mt-3"style="border:0;">
        <div class="row">
            <div class="cd card  p-3 mb-5 bg-body rounded mb-4">
                <img src="{{data.image.url}}" class="card-img-top rounded-2 ms-2 mt-3" alt="...">
                <div class="card-body">
                
      
                
                </div>
            </div>
                <div class="col2 col-5 ms-2">
                    <h2>{{data.name}}</h2>
                    <h3>${{data.price}}</h3>
                    
                    <h5 class="ct mt-3">category: {{data.category}}</h5> 
                    {% if data.stock >= 1 %}   
                    <!-- <button class="btn btn-primary me-3">Add to cart</button> -->
                    <a href="{% url 'cartapp:addcart' data.id %}" type="button" class="btn btn-warning me-3 p-3">add to cart</a>
                    <button class="btn btn-danger me-3">Buy Now</button>
                    
                    {% else %}
                    <span><h3 class="out" style="color: green;">out of stock</h3></span>
                    {% endif %}
  
                </div>
          </div>
    </div>
        
</div>

{% endblock %}

Todoproject/templates/footer.html
<nav class="navbar bg-dark navbar-dark">
    <div class="container-fluid p-0">
      <span class="navbar-brand mb-0 mx-auto h1">footer</span>
    </div>
  </nav>
  

Todoproject/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

 {% if category %}
<div class="container-fluid mb-3">

 <h1 class="hed mt-5 mb-2">{{category.name}}</h1>
 <img class="can rounded-5 " src="{{category.image.url}}" style="margin-left: 35%;" width="30%" height="500" alt="">
 <h5 class="des mt-4 mb-5">{{category.desc}}</h5></div>

 {% else %}
<div class="container-fluid mb-3">

 <h1 class="hed mt-5 mb-2">All Products</h1>
 <img class="can rounded-5 " src="../static/images/store.png" style="margin-left: 30px;" width="96%" height="600" alt="">
 <h5 class="des mt-4 mb-5">A mobile phone (or cellphone[a]) is a portable telephone that can make and receive calls over a radio frequency link while the user is moving within a telephone service area, as opposed to a fixed-location phone (landline phone). The radio frequency link establishes a connection to the switching systems of a mobile phone operator</h5></div>

 {% endif %}
<div class="container-fluid">
    <div class="card-group mb-3">
      {% for i in products %}
        {% if i.available %}
        <a href="{% url 'shop:details' i.id %}">
        <div class="cad border p-5 mb-5 bg-body rounded mb-4 me-4">
          <img src="{{i.image.url}}" height="400px" class="card-img-top rounded-4 " alt="...">
          <div class="card-body">
            <h3 class="card-title">{{i.name}}</h3>
            <h5 class="card-text">${{i.price}}</h5>
            <h6 class="card-text">{{i.category}}</h6>
          </div>
        </div>
        </a>
        {% endif %}
        {% endfor %}
      </div>
</div>





<!-- paginator -->
<div class="paginator mx-auto">
  {% if products.paginator.num_pages > 1 %}<hr>

   <div class="text-center">
    {% for pg in products.paginator.page_range %}
    <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
    {% endfor %}
   </div>
   {% endif %}


</div>


{% endblock %}

Todoproject/templates/loginuser.html
{% extends 'base.html' %}
{% block content %}
<div class="kk container mt-5 rounded-3 bg-light  login_page">
    <form action="" method="post">
        {% csrf_token %}
        <h3 class="login text-center pt-3">LogIn</h3>
        <div class="form-group login_input  pt-4 ">
            <input type="text" class="form-control" placeholder="Username" name="username">
        </div>
        <div class="form-group  login_input pt-1 ">
            <input type="password" class="form-control" placeholder="Password" name="password">
        </div>
        <div class="form-group  login_input  pt-2 ">
            <button type="submit" class=" ab btn btn-primary">Login</button>
        </div>
    </form>
</div>

</div>
</div>
</div>
</div>

{% endblock %}

Todoproject/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">E-commerse</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:home' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:home' %}">ALL products</a></li>
            {% for link in links %}
            <li><a class="dropdown-item" href="{{link.get_url}}">{{link.name}}</a></li>

            {% endfor %}

          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search" action="{% url 'searchapp:searchproduct' %}" method="GET">
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <a class="pt-4" href="{% url 'cartapp:displaycart' %}"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path fill="yellow" d="M280-80q-33 0-56.5-23.5T200-160q0-33 23.5-56.5T280-240q33 0 56.5 23.5T360-160q0 33-23.5 56.5T280-80Zm400 0q-33 0-56.5-23.5T600-160q0-33 23.5-56.5T680-240q33 0 56.5 23.5T760-160q0 33-23.5 56.5T680-80ZM246-720l96 200h280l110-200H246Zm-38-80h590q23 0 35 20.5t1 41.5L692-482q-11 20-29.5 31T622-440H324l-44 80h480v80H280q-45 0-68-39.5t-2-78.5l54-98-144-304H40v-80h130l38 80Zm134 280h280-280Z"/></svg></a>
      </form>
      <div class="d-flex">
        {% if user.is_authenticated %}

        <span class="text-light">{{user}}</span>
        <a href="{% url 'auth:logout' %}" class="btn btn-outline-danger" type="button">Logout</a>
        {% else %}
        <a href="{% url 'auth:login' %}" class="btn btn-outline-success me-2" type="button">Login</a>
        <a href="{% url 'auth:register' %}" class="btn btn-outline-primary me-2" type="button">Signup</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>

Todoproject/templates/registeruser.html
{% extends 'base.html' %}
{% block content %}
<form action6="" method="post" class=" reg bg-light p-3 mt-2 rounded mx-auto " >
    {% csrf_token %}
    <h2 class="signup text-center">SIGN UP</h2>
    <div class="mb-3">
        <label for="fname" class="form-label">First Name</label>
        <input type="text" class="form-control" id="fname" placeholder="First Name" name="fname">
    </div>
    <div class="mb-3">
        <label for="lname" class="form-label">Last Name</label>
        <input type="text" class="form-control" id="lname" placeholder="Last Name" name="lname">
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" placeholder="Email" name="email">
    </div>
    <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" id="username" placeholder="Username" name="username">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" placeholder="Password" name="password">
    </div>
    <div class="mb-3">
        <label for="cpassword" class="form-label">Confirm Password</label>
        <input type="password" class="form-control" id="cpassword" placeholder="Confirm Password" name="cpassword">
    </div>
    <div>
        <button type="submit" class=" ac  btn btn-primary">Submit</button>
    </div>
</form>

{% endblock %}

Todoproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="card-group mb-3">
      {% for i in products %}
        
        <a href="{% url 'shop:details' i.id %}">
        <div class="cad border p-5 mb-5 bg-body rounded mb-4 me-4">
          <img src="{{i.image.url}}" height="400px" class="card-img-top rounded-4 " alt="...">
          <div class="card-body">
            <h3 class="card-title">{{i.name}}</h3>
            <h5 class="card-text">${{i.price}}</h5>
            <h6 class="card-text">{{i.category}}</h6>
          </div>
        </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}